package com.circulation.circulation_networks.gui.component.base;

/**
 * IDE-friendly placeholder for the generated component atlas registration class.
 *
 * <p>This source file exists only so the editor can resolve
 * {@link GeneratedComponentAtlasRegistration} while you are editing code,
 * before the Gradle generation task has run. Without this placeholder,
 * references from {@link ComponentAtlas} to the generated registration class
 * would appear as unresolved in the IDE and would negatively affect code
 * completion, navigation, inspections, and general editing experience.
 *
 * <p>The real implementation is generated automatically during the build by the
 * {@code generateComponentAtlasRegistration} Gradle task. That generated class
 * scans the current atlas resource directories and emits concrete registration
 * code for all discovered textures.
 *
 * <p>The generated implementation typically contains calls equivalent to:
 * <ul>
 * <li>registering every component texture under
 *     {@code assets/<modid>/textures/gui/component}</li>
 * <li>registering every atlas texture under
 *     {@code assets/<modid>/textures/gui/component}</li>
 * <li>emitting explicit {@code event.register(...)} statements for those files</li>
 * </ul>
 *
 * <p>Manual edits to this placeholder are functionally meaningless for runtime
 * behavior. They do not change the actual atlas registration used by the game,
 * because the build-generated class is the implementation that is compiled into
 * the main runtime artifact.
 *
 * <p>If atlas registration contents need to change, do not edit this file.
 * Instead, change one of the following inputs:
 * <ul>
 * <li>the textures present in {@code assets/<modid>/textures/gui/component}</li>
 * <li>the Gradle generation logic in the build script</li>
 * </ul>
 *
 * <p>In short: this file is documentation and IDE scaffolding only.
 */
@SuppressWarnings({"JavadocReference", "unused"})
public final class GeneratedComponentAtlasRegistration {

    private GeneratedComponentAtlasRegistration() {
    }

    /**
     * No-op placeholder method for IDE symbol resolution.
     *
     * <p>The generated runtime class provides the real method body and emits the
    * actual registration calls for atlas textures. This placeholder accepts
     * {@link Object} intentionally so it does not depend on main-source types
     * during API-source compilation.
     *
     * <p>Do not add logic here. Any manual implementation would be ignored as far
     * as the real generated registration flow is concerned.
     */
    public static void register(Object event) {
        // Intentionally empty.
    }
}